<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 20 Comparação entre dois grupos | Estatística + R</title>
  <meta name="description" content="Capítulo 20 Comparação entre dois grupos | Estatística + R" />
  <meta name="generator" content="bookdown 0.42.2 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 20 Comparação entre dois grupos | Estatística + R" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 20 Comparação entre dois grupos | Estatística + R" />
  
  
  

<meta name="author" content="Ana Paula Fernandes (DESCO/ICS/UFTM)" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="testes-de-comparação-entre-grupos.html"/>
<link rel="next" href="cálculo-amostral-no-r.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/viz-1.8.2/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.11/grViz.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<h2><center>Estatística + R</center></h2>
<center> ISBN 978-65-01-56980-2 </center>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Bem-vindos!</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introdução</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#atividade-1"><i class="fa fa-check"></i><b>2.1</b> Atividade 1</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="definições-iniciais.html"><a href="definições-iniciais.html"><i class="fa fa-check"></i><b>3</b> Definições Iniciais</a>
<ul>
<li class="chapter" data-level="3.1" data-path="definições-iniciais.html"><a href="definições-iniciais.html#estatística-descritiva"><i class="fa fa-check"></i><b>3.1</b> Estatística Descritiva</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="definições-iniciais.html"><a href="definições-iniciais.html#exemplo-1-saúde-mental-dos-estudantes"><i class="fa fa-check"></i><b>3.1.1</b> Exemplo 1: <strong>Saúde Mental dos Estudantes</strong></a></li>
<li class="chapter" data-level="3.1.2" data-path="definições-iniciais.html"><a href="definições-iniciais.html#exemplo-2-prática-de-atividades-físicas"><i class="fa fa-check"></i><b>3.1.2</b> Exemplo 2: <strong>Prática de Atividades Físicas</strong></a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="definições-iniciais.html"><a href="definições-iniciais.html#estatística-inferencial"><i class="fa fa-check"></i><b>3.2</b> Estatística Inferencial</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="definições-iniciais.html"><a href="definições-iniciais.html#exemplo-1-saúde-mental-dos-estudantes-1"><i class="fa fa-check"></i><b>3.2.1</b> Exemplo 1: <strong>Saúde Mental dos Estudantes</strong></a></li>
<li class="chapter" data-level="3.2.2" data-path="definições-iniciais.html"><a href="definições-iniciais.html#exemplo-2-prática-de-atividades-físicas-1"><i class="fa fa-check"></i><b>3.2.2</b> Exemplo 2: <strong>Prática de Atividades Físicas</strong></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="definições-iniciais.html"><a href="definições-iniciais.html#conexão-com-a-probabilidade"><i class="fa fa-check"></i><b>3.3</b> Conexão com a Probabilidade</a></li>
<li class="chapter" data-level="3.4" data-path="definições-iniciais.html"><a href="definições-iniciais.html#população-x-amostra"><i class="fa fa-check"></i><b>3.4</b> População x Amostra</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="definições-iniciais.html"><a href="definições-iniciais.html#população"><i class="fa fa-check"></i><b>3.4.1</b> <strong>População</strong></a></li>
<li class="chapter" data-level="3.4.2" data-path="definições-iniciais.html"><a href="definições-iniciais.html#amostra"><i class="fa fa-check"></i><b>3.4.2</b> <strong>Amostra</strong></a></li>
<li class="chapter" data-level="3.4.3" data-path="definições-iniciais.html"><a href="definições-iniciais.html#exemplo-aplicado"><i class="fa fa-check"></i><b>3.4.3</b> <strong>Exemplo aplicado</strong></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tamanho-da-amostra.html"><a href="tamanho-da-amostra.html"><i class="fa fa-check"></i><b>4</b> Tamanho da Amostra</a>
<ul>
<li class="chapter" data-level="4.1" data-path="tamanho-da-amostra.html"><a href="tamanho-da-amostra.html#passos-básicos-para-o-cálculo-do-tamanho-da-amostra"><i class="fa fa-check"></i><b>4.1</b> Passos básicos para o cálculo do tamanho da amostra</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="tamanho-da-amostra.html"><a href="tamanho-da-amostra.html#exemplo-de-cálculo-simples"><i class="fa fa-check"></i><b>4.1.1</b> Exemplo de cálculo simples</a></li>
<li class="chapter" data-level="4.1.2" data-path="tamanho-da-amostra.html"><a href="tamanho-da-amostra.html#ferramentas-para-cálculo-de-amostra"><i class="fa fa-check"></i><b>4.1.2</b> Ferramentas para cálculo de amostra</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="tamanho-da-amostra.html"><a href="tamanho-da-amostra.html#cálculo-do-tamanho-da-amostra"><i class="fa fa-check"></i><b>4.2</b> Cálculo do Tamanho da Amostra</a></li>
<li class="chapter" data-level="4.3" data-path="tamanho-da-amostra.html"><a href="tamanho-da-amostra.html#conclusão"><i class="fa fa-check"></i><b>4.3</b> Conclusão</a></li>
<li class="chapter" data-level="4.4" data-path="tamanho-da-amostra.html"><a href="tamanho-da-amostra.html#atividade-2"><i class="fa fa-check"></i><b>4.4</b> Atividade 2</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="técnicas-de-amostragem.html"><a href="técnicas-de-amostragem.html"><i class="fa fa-check"></i><b>5</b> Técnicas de Amostragem</a>
<ul>
<li class="chapter" data-level="5.1" data-path="técnicas-de-amostragem.html"><a href="técnicas-de-amostragem.html#amostragem-aleatória-simples"><i class="fa fa-check"></i><b>5.1</b> Amostragem Aleatória Simples</a></li>
<li class="chapter" data-level="5.2" data-path="técnicas-de-amostragem.html"><a href="técnicas-de-amostragem.html#amostragem-estratificada"><i class="fa fa-check"></i><b>5.2</b> Amostragem Estratificada</a></li>
<li class="chapter" data-level="5.3" data-path="técnicas-de-amostragem.html"><a href="técnicas-de-amostragem.html#amostragem-sistemática"><i class="fa fa-check"></i><b>5.3</b> Amostragem Sistemática</a></li>
<li class="chapter" data-level="5.4" data-path="técnicas-de-amostragem.html"><a href="técnicas-de-amostragem.html#amostragem-por-conglomerados"><i class="fa fa-check"></i><b>5.4</b> Amostragem por Conglomerados</a></li>
<li class="chapter" data-level="5.5" data-path="técnicas-de-amostragem.html"><a href="técnicas-de-amostragem.html#amostragem-por-conveniência"><i class="fa fa-check"></i><b>5.5</b> Amostragem por Conveniência</a></li>
<li class="chapter" data-level="5.6" data-path="técnicas-de-amostragem.html"><a href="técnicas-de-amostragem.html#combinando-técnicas-na-prática"><i class="fa fa-check"></i><b>5.6</b> Combinando Técnicas na Prática</a></li>
<li class="chapter" data-level="5.7" data-path="técnicas-de-amostragem.html"><a href="técnicas-de-amostragem.html#evitar-viés-na-amostragem"><i class="fa fa-check"></i><b>5.7</b> Evitar Viés na Amostragem</a></li>
<li class="chapter" data-level="5.8" data-path="técnicas-de-amostragem.html"><a href="técnicas-de-amostragem.html#resumindo"><i class="fa fa-check"></i><b>5.8</b> Resumindo</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ambiente-computacional.html"><a href="ambiente-computacional.html"><i class="fa fa-check"></i><b>6</b> Ambiente Computacional</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ambiente-computacional.html"><a href="ambiente-computacional.html#softwares-pagos"><i class="fa fa-check"></i><b>6.1</b> Softwares pagos</a></li>
<li class="chapter" data-level="6.2" data-path="ambiente-computacional.html"><a href="ambiente-computacional.html#softwares-livres"><i class="fa fa-check"></i><b>6.2</b> Softwares livres</a></li>
<li class="chapter" data-level="6.3" data-path="ambiente-computacional.html"><a href="ambiente-computacional.html#linguagens-computacionais"><i class="fa fa-check"></i><b>6.3</b> Linguagens computacionais</a></li>
<li class="chapter" data-level="6.4" data-path="ambiente-computacional.html"><a href="ambiente-computacional.html#preparando-o-ambiente-computacional"><i class="fa fa-check"></i><b>6.4</b> Preparando o Ambiente Computacional</a></li>
<li class="chapter" data-level="6.5" data-path="ambiente-computacional.html"><a href="ambiente-computacional.html#plano-a-instalação-do-r-e-rstudio"><i class="fa fa-check"></i><b>6.5</b> Plano A: Instalação do R e RStudio</a></li>
<li class="chapter" data-level="6.6" data-path="ambiente-computacional.html"><a href="ambiente-computacional.html#plano-b-r-e-rstudio-na-nuvem"><i class="fa fa-check"></i><b>6.6</b> Plano B: R e RStudio na Nuvem</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="trabalhando-RStudio.html"><a href="trabalhando-RStudio.html"><i class="fa fa-check"></i><b>7</b> Trabalhando no RStudio</a></li>
<li class="chapter" data-level="8" data-path="primeiros-exercícios-no-r.html"><a href="primeiros-exercícios-no-r.html"><i class="fa fa-check"></i><b>8</b> Primeiros exercícios no R</a>
<ul>
<li class="chapter" data-level="8.1" data-path="primeiros-exercícios-no-r.html"><a href="primeiros-exercícios-no-r.html#exemplo-1"><i class="fa fa-check"></i><b>8.1</b> Exemplo 1</a></li>
<li class="chapter" data-level="8.2" data-path="primeiros-exercícios-no-r.html"><a href="primeiros-exercícios-no-r.html#exemplo-2"><i class="fa fa-check"></i><b>8.2</b> Exemplo 2</a></li>
<li class="chapter" data-level="8.3" data-path="primeiros-exercícios-no-r.html"><a href="primeiros-exercícios-no-r.html#exemplo-3"><i class="fa fa-check"></i><b>8.3</b> Exemplo 3</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="tipos-de-variáveis.html"><a href="tipos-de-variáveis.html"><i class="fa fa-check"></i><b>9</b> Tipos de Variáveis</a>
<ul>
<li class="chapter" data-level="9.1" data-path="tipos-de-variáveis.html"><a href="tipos-de-variáveis.html#variáveis-quantitativas"><i class="fa fa-check"></i><b>9.1</b> Variáveis Quantitativas</a></li>
<li class="chapter" data-level="9.2" data-path="tipos-de-variáveis.html"><a href="tipos-de-variáveis.html#variáveis-qualitativas"><i class="fa fa-check"></i><b>9.2</b> Variáveis Qualitativas</a></li>
<li class="chapter" data-level="9.3" data-path="tipos-de-variáveis.html"><a href="tipos-de-variáveis.html#aplicação-das-variáveis-em-estatística"><i class="fa fa-check"></i><b>9.3</b> Aplicação das Variáveis em Estatística</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="tipos-de-variáveis.html"><a href="tipos-de-variáveis.html#estatística-descritiva-1"><i class="fa fa-check"></i><b>9.3.1</b> Estatística Descritiva:</a></li>
<li class="chapter" data-level="9.3.2" data-path="tipos-de-variáveis.html"><a href="tipos-de-variáveis.html#estatística-inferencial-1"><i class="fa fa-check"></i><b>9.3.2</b> Estatística Inferencial:</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="tipos-de-variáveis.html"><a href="tipos-de-variáveis.html#atividade-3"><i class="fa fa-check"></i><b>9.4</b> Atividade 3</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="tipos-de-variáveis.html"><a href="tipos-de-variáveis.html#análise-das-tabelas"><i class="fa fa-check"></i><b>9.4.1</b> Análise das Tabelas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html"><i class="fa fa-check"></i><b>10</b> Estatística Descritiva</a>
<ul>
<li class="chapter" data-level="10.1" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#medidas-de-tendência-central-ou-posição"><i class="fa fa-check"></i><b>10.1</b> Medidas de Tendência Central (ou Posição)</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#média"><i class="fa fa-check"></i><b>10.1.1</b> Média</a></li>
<li class="chapter" data-level="10.1.2" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#mediana"><i class="fa fa-check"></i><b>10.1.2</b> Mediana</a></li>
<li class="chapter" data-level="10.1.3" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#quartis"><i class="fa fa-check"></i><b>10.1.3</b> Quartis</a></li>
<li class="chapter" data-level="10.1.4" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#moda"><i class="fa fa-check"></i><b>10.1.4</b> Moda</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#medidas-de-dispersão-ou-variabilidade"><i class="fa fa-check"></i><b>10.2</b> Medidas de Dispersão (ou Variabilidade)</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#amplitude"><i class="fa fa-check"></i><b>10.2.1</b> Amplitude</a></li>
<li class="chapter" data-level="10.2.2" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#variância"><i class="fa fa-check"></i><b>10.2.2</b> Variância</a></li>
<li class="chapter" data-level="10.2.3" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#desvio-padrão-dp"><i class="fa fa-check"></i><b>10.2.3</b> Desvio padrão (DP)</a></li>
<li class="chapter" data-level="10.2.4" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#amplitude-interquartil-iqr"><i class="fa fa-check"></i><b>10.2.4</b> Amplitude interquartil (IQR)</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#medida-relativa-de-variabilidade"><i class="fa fa-check"></i><b>10.3</b> Medida Relativa de Variabilidade</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#coeficiente-de-variação-cv"><i class="fa fa-check"></i><b>10.3.1</b> Coeficiente de Variação (CV)</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#apresentação-dos-resultados"><i class="fa fa-check"></i><b>10.4</b> Apresentação dos Resultados</a></li>
<li class="chapter" data-level="10.5" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#funções-no-r"><i class="fa fa-check"></i><b>10.5</b> Funções no R</a></li>
<li class="chapter" data-level="10.6" data-path="estatística-descritiva-2.html"><a href="estatística-descritiva-2.html#atividade-4"><i class="fa fa-check"></i><b>10.6</b> Atividade 4</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="importando-banco-de-dados.html"><a href="importando-banco-de-dados.html"><i class="fa fa-check"></i><b>11</b> Importando banco de dados</a>
<ul>
<li class="chapter" data-level="11.1" data-path="importando-banco-de-dados.html"><a href="importando-banco-de-dados.html#importando-um-banco-csv"><i class="fa fa-check"></i><b>11.1</b> Importando um banco csv</a></li>
<li class="chapter" data-level="11.2" data-path="importando-banco-de-dados.html"><a href="importando-banco-de-dados.html#importando-um-banco-xls"><i class="fa fa-check"></i><b>11.2</b> Importando um banco xls</a></li>
<li class="chapter" data-level="11.3" data-path="importando-banco-de-dados.html"><a href="importando-banco-de-dados.html#exemplo-1-1"><i class="fa fa-check"></i><b>11.3</b> Exemplo 1</a></li>
<li class="chapter" data-level="11.4" data-path="importando-banco-de-dados.html"><a href="importando-banco-de-dados.html#exemplo-2-1"><i class="fa fa-check"></i><b>11.4</b> Exemplo 2</a></li>
<li class="chapter" data-level="11.5" data-path="importando-banco-de-dados.html"><a href="importando-banco-de-dados.html#exemplo-3-1"><i class="fa fa-check"></i><b>11.5</b> Exemplo 3</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="instalando-pacotes.html"><a href="instalando-pacotes.html"><i class="fa fa-check"></i><b>12</b> Instalando pacotes</a>
<ul>
<li class="chapter" data-level="12.1" data-path="instalando-pacotes.html"><a href="instalando-pacotes.html#exemplo-1-2"><i class="fa fa-check"></i><b>12.1</b> Exemplo 1</a></li>
<li class="chapter" data-level="12.2" data-path="instalando-pacotes.html"><a href="instalando-pacotes.html#exemplo-2-2"><i class="fa fa-check"></i><b>12.2</b> Exemplo 2</a></li>
<li class="chapter" data-level="12.3" data-path="instalando-pacotes.html"><a href="instalando-pacotes.html#exemplo-3-2"><i class="fa fa-check"></i><b>12.3</b> Exemplo 3</a></li>
<li class="chapter" data-level="12.4" data-path="instalando-pacotes.html"><a href="instalando-pacotes.html#exemplo-4"><i class="fa fa-check"></i><b>12.4</b> Exemplo 4</a></li>
<li class="chapter" data-level="12.5" data-path="instalando-pacotes.html"><a href="instalando-pacotes.html#atividade-5"><i class="fa fa-check"></i><b>12.5</b> Atividade 5</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="gráficos.html"><a href="gráficos.html"><i class="fa fa-check"></i><b>13</b> Gráficos</a>
<ul>
<li class="chapter" data-level="13.1" data-path="gráficos.html"><a href="gráficos.html#histograma"><i class="fa fa-check"></i><b>13.1</b> Histograma</a></li>
<li class="chapter" data-level="13.2" data-path="gráficos.html"><a href="gráficos.html#boxplot"><i class="fa fa-check"></i><b>13.2</b> Boxplot</a></li>
<li class="chapter" data-level="13.3" data-path="gráficos.html"><a href="gráficos.html#atividade-6"><i class="fa fa-check"></i><b>13.3</b> Atividade 6</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="pacote-ggplot.html"><a href="pacote-ggplot.html"><i class="fa fa-check"></i><b>14</b> Pacote <code>ggplot</code></a>
<ul>
<li class="chapter" data-level="14.1" data-path="pacote-ggplot.html"><a href="pacote-ggplot.html#principais-vantagens"><i class="fa fa-check"></i><b>14.1</b> Principais Vantagens</a></li>
<li class="chapter" data-level="14.2" data-path="pacote-ggplot.html"><a href="pacote-ggplot.html#exemplos-de-gráficos-simples-e-bonitos-com-ggplot2"><i class="fa fa-check"></i><b>14.2</b> Exemplos de Gráficos Simples e Bonitos com ggplot2</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="pacote-ggplot.html"><a href="pacote-ggplot.html#gráfico-de-dispersão-scatterplot"><i class="fa fa-check"></i><b>14.2.1</b> Gráfico de Dispersão (Scatterplot)</a></li>
<li class="chapter" data-level="14.2.2" data-path="pacote-ggplot.html"><a href="pacote-ggplot.html#gráfico-de-barras"><i class="fa fa-check"></i><b>14.2.2</b> Gráfico de Barras</a></li>
<li class="chapter" data-level="14.2.3" data-path="pacote-ggplot.html"><a href="pacote-ggplot.html#histograma-1"><i class="fa fa-check"></i><b>14.2.3</b> Histograma</a></li>
<li class="chapter" data-level="14.2.4" data-path="pacote-ggplot.html"><a href="pacote-ggplot.html#boxplot-1"><i class="fa fa-check"></i><b>14.2.4</b> Boxplot</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="pacote-ggplot.html"><a href="pacote-ggplot.html#exemplos-de-bancos-de-dados-do-r"><i class="fa fa-check"></i><b>14.3</b> Exemplos de Bancos de Dados do R</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="distribuição-de-probabilidade.html"><a href="distribuição-de-probabilidade.html"><i class="fa fa-check"></i><b>15</b> Distribuição de Probabilidade</a>
<ul>
<li class="chapter" data-level="15.1" data-path="distribuição-de-probabilidade.html"><a href="distribuição-de-probabilidade.html#distribuição-normal"><i class="fa fa-check"></i><b>15.1</b> Distribuição Normal</a></li>
<li class="chapter" data-level="15.2" data-path="distribuição-de-probabilidade.html"><a href="distribuição-de-probabilidade.html#gráfico-qq"><i class="fa fa-check"></i><b>15.2</b> Gráfico QQ</a></li>
<li class="chapter" data-level="15.3" data-path="distribuição-de-probabilidade.html"><a href="distribuição-de-probabilidade.html#atividade-7"><i class="fa fa-check"></i><b>15.3</b> Atividade 7</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="exemplos-de-distribuições.html"><a href="exemplos-de-distribuições.html"><i class="fa fa-check"></i><b>16</b> Exemplos de distribuições</a>
<ul>
<li class="chapter" data-level="16.1" data-path="exemplos-de-distribuições.html"><a href="exemplos-de-distribuições.html#distribuições-discretas"><i class="fa fa-check"></i><b>16.1</b> Distribuições Discretas</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="exemplos-de-distribuições.html"><a href="exemplos-de-distribuições.html#binomial"><i class="fa fa-check"></i><b>16.1.1</b> Binomial</a></li>
<li class="chapter" data-level="16.1.2" data-path="exemplos-de-distribuições.html"><a href="exemplos-de-distribuições.html#poisson"><i class="fa fa-check"></i><b>16.1.2</b> Poisson</a></li>
<li class="chapter" data-level="16.1.3" data-path="exemplos-de-distribuições.html"><a href="exemplos-de-distribuições.html#geométrica"><i class="fa fa-check"></i><b>16.1.3</b> Geométrica</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="exemplos-de-distribuições.html"><a href="exemplos-de-distribuições.html#distribuições-contínuas"><i class="fa fa-check"></i><b>16.2</b> Distribuições Contínuas</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="exemplos-de-distribuições.html"><a href="exemplos-de-distribuições.html#normal"><i class="fa fa-check"></i><b>16.2.1</b> Normal</a></li>
<li class="chapter" data-level="16.2.2" data-path="exemplos-de-distribuições.html"><a href="exemplos-de-distribuições.html#exponencial"><i class="fa fa-check"></i><b>16.2.2</b> Exponencial</a></li>
<li class="chapter" data-level="16.2.3" data-path="exemplos-de-distribuições.html"><a href="exemplos-de-distribuições.html#uniforme-contínua"><i class="fa fa-check"></i><b>16.2.3</b> Uniforme Contínua</a></li>
<li class="chapter" data-level="16.2.4" data-path="exemplos-de-distribuições.html"><a href="exemplos-de-distribuições.html#t-de-student"><i class="fa fa-check"></i><b>16.2.4</b> t de Student</a></li>
<li class="chapter" data-level="16.2.5" data-path="exemplos-de-distribuições.html"><a href="exemplos-de-distribuições.html#qui-quadrado-χ²"><i class="fa fa-check"></i><b>16.2.5</b> Qui-Quadrado (χ²)</a></li>
<li class="chapter" data-level="16.2.6" data-path="exemplos-de-distribuições.html"><a href="exemplos-de-distribuições.html#f-de-fisher"><i class="fa fa-check"></i><b>16.2.6</b> F de Fisher</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="normal-ou-não.html"><a href="normal-ou-não.html"><i class="fa fa-check"></i><b>17</b> Normal ou Não?</a>
<ul>
<li class="chapter" data-level="17.1" data-path="normal-ou-não.html"><a href="normal-ou-não.html#dados-que-seguem-distribuição-normal"><i class="fa fa-check"></i><b>17.1</b> Dados que seguem distribuição normal</a></li>
<li class="chapter" data-level="17.2" data-path="normal-ou-não.html"><a href="normal-ou-não.html#dados-que-geram-dúvida"><i class="fa fa-check"></i><b>17.2</b> Dados que geram dúvida</a></li>
<li class="chapter" data-level="17.3" data-path="normal-ou-não.html"><a href="normal-ou-não.html#dados-que-não-seguem-distribuição-normal"><i class="fa fa-check"></i><b>17.3</b> Dados que não seguem distribuição normal</a></li>
<li class="chapter" data-level="17.4" data-path="normal-ou-não.html"><a href="normal-ou-não.html#dados-com-forte-concentração-de-repetição-de-valor-não-seguem-distribuição-normal"><i class="fa fa-check"></i><b>17.4</b> Dados com forte concentração de repetição de valor (não seguem distribuição normal)</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html"><i class="fa fa-check"></i><b>18</b> Estatística Inferencial</a>
<ul>
<li class="chapter" data-level="18.1" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html#etapas-de-um-teste-estatístico"><i class="fa fa-check"></i><b>18.1</b> Etapas de um Teste Estatístico</a></li>
<li class="chapter" data-level="18.2" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html#erros-tipo-i-e-tipo-ii"><i class="fa fa-check"></i><b>18.2</b> Erros Tipo I e Tipo II</a></li>
<li class="chapter" data-level="18.3" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html#poder-do-teste-estatístico"><i class="fa fa-check"></i><b>18.3</b> Poder do Teste Estatístico</a></li>
<li class="chapter" data-level="18.4" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html#tabela-erros-decisões-e-poder-do-teste"><i class="fa fa-check"></i><b>18.4</b> Tabela: Erros, Decisões e Poder do Teste</a></li>
<li class="chapter" data-level="18.5" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html#tamanho-do-efeito"><i class="fa fa-check"></i><b>18.5</b> Tamanho do Efeito</a>
<ul>
<li class="chapter" data-level="18.5.1" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html#o-que-é-o-tamanho-do-efeito"><i class="fa fa-check"></i><b>18.5.1</b> O que é o Tamanho do Efeito?</a></li>
<li class="chapter" data-level="18.5.2" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html#exemplos-para-entender-melhor"><i class="fa fa-check"></i><b>18.5.2</b> Exemplos para Entender Melhor</a></li>
</ul></li>
<li class="chapter" data-level="18.6" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html#medidas-comuns-de-tamanho-do-efeito"><i class="fa fa-check"></i><b>18.6</b> Medidas Comuns de Tamanho do Efeito</a>
<ul>
<li class="chapter" data-level="18.6.1" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html#d-de-cohen-teste-t"><i class="fa fa-check"></i><b>18.6.1</b> d de Cohen (teste t)</a></li>
<li class="chapter" data-level="18.6.2" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html#c-de-cramer-para-tabela-2x2-teste-qui-quadrado"><i class="fa fa-check"></i><b>18.6.2</b> C de Cramer, para tabela 2x2 (teste qui-quadrado)</a></li>
<li class="chapter" data-level="18.6.3" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html#coeficiente-de-correlação-de-pearson-r"><i class="fa fa-check"></i><b>18.6.3</b> Coeficiente de Correlação de Pearson (r)</a></li>
</ul></li>
<li class="chapter" data-level="18.7" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html#por-que-o-tamanho-do-efeito-é-importante"><i class="fa fa-check"></i><b>18.7</b> Por que o Tamanho do Efeito é Importante?</a></li>
<li class="chapter" data-level="18.8" data-path="estatística-inferencial-2.html"><a href="estatística-inferencial-2.html#testes"><i class="fa fa-check"></i><b>18.8</b> Testes</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="testes-de-comparação-entre-grupos.html"><a href="testes-de-comparação-entre-grupos.html"><i class="fa fa-check"></i><b>19</b> Testes de Comparação entre Grupos</a>
<ul>
<li class="chapter" data-level="19.1" data-path="testes-de-comparação-entre-grupos.html"><a href="testes-de-comparação-entre-grupos.html#comparações-pareadas-dependentes"><i class="fa fa-check"></i><b>19.1</b> Comparações Pareadas (Dependentes)</a></li>
<li class="chapter" data-level="19.2" data-path="testes-de-comparação-entre-grupos.html"><a href="testes-de-comparação-entre-grupos.html#comparações-não-pareadas-independentes"><i class="fa fa-check"></i><b>19.2</b> Comparações Não-Pareadas (Independentes)</a></li>
<li class="chapter" data-level="19.3" data-path="testes-de-comparação-entre-grupos.html"><a href="testes-de-comparação-entre-grupos.html#número-de-grupos-na-comparação"><i class="fa fa-check"></i><b>19.3</b> Número de Grupos na Comparação</a></li>
<li class="chapter" data-level="19.4" data-path="testes-de-comparação-entre-grupos.html"><a href="testes-de-comparação-entre-grupos.html#testes-paramétricos-e-não-paramétricos"><i class="fa fa-check"></i><b>19.4</b> Testes Paramétricos e Não Paramétricos</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html"><i class="fa fa-check"></i><b>20</b> Comparação entre dois grupos</a>
<ul>
<li class="chapter" data-level="20.1" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#teste-t-pareado"><i class="fa fa-check"></i><b>20.1</b> Teste t pareado</a></li>
<li class="chapter" data-level="20.2" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#wilcoxon-pareado"><i class="fa fa-check"></i><b>20.2</b> Wilcoxon pareado</a></li>
<li class="chapter" data-level="20.3" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#teste-t-não-pareado"><i class="fa fa-check"></i><b>20.3</b> Teste t não pareado</a>
<ul>
<li class="chapter" data-level="20.3.1" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#teste-de-variância"><i class="fa fa-check"></i><b>20.3.1</b> Teste de variância</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#wilcoxon-não-pareado"><i class="fa fa-check"></i><b>20.4</b> Wilcoxon não pareado</a></li>
<li class="chapter" data-level="20.5" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#teste-bilateral-vs.-teste-unilateral"><i class="fa fa-check"></i><b>20.5</b> Teste bilateral vs. teste unilateral</a>
<ul>
<li class="chapter" data-level="20.5.1" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#o-que-são"><i class="fa fa-check"></i><b>20.5.1</b> O que são?</a></li>
<li class="chapter" data-level="20.5.2" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#formulação-das-hipóteses"><i class="fa fa-check"></i><b>20.5.2</b> Formulação das hipóteses</a></li>
<li class="chapter" data-level="20.5.3" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#influência-no-cálculo-do-p-valor"><i class="fa fa-check"></i><b>20.5.3</b> Influência no cálculo do p-valor</a></li>
<li class="chapter" data-level="20.5.4" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#o-que-muda-nas-funções-t.test-e-wilcox.test"><i class="fa fa-check"></i><b>20.5.4</b> O que muda nas funções <code>t.test()</code> e <code>wilcox.test()</code></a></li>
</ul></li>
<li class="chapter" data-level="20.6" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#exercício-1"><i class="fa fa-check"></i><b>20.6</b> Exercício 1</a></li>
<li class="chapter" data-level="20.7" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#exercício-2"><i class="fa fa-check"></i><b>20.7</b> Exercício 2</a></li>
<li class="chapter" data-level="20.8" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#exercício-3"><i class="fa fa-check"></i><b>20.8</b> Exercício 3</a></li>
<li class="chapter" data-level="20.9" data-path="comparação-entre-dois-grupos.html"><a href="comparação-entre-dois-grupos.html#exercício-4"><i class="fa fa-check"></i><b>20.9</b> Exercício 4</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html"><i class="fa fa-check"></i><b>21</b> Cálculo amostral no R</a>
<ul>
<li class="chapter" data-level="21.1" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#principais-pacotes-para-cálculo-amostral"><i class="fa fa-check"></i><b>21.1</b> Principais Pacotes para Cálculo Amostral</a></li>
<li class="chapter" data-level="21.2" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#exemplo-de-cálculo-amostral-para-teste-t"><i class="fa fa-check"></i><b>21.2</b> Exemplo de cálculo amostral para teste t</a></li>
<li class="chapter" data-level="21.3" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#o-que-é-o-d-de-cohen"><i class="fa fa-check"></i><b>21.3</b> O que é o d de Cohen?</a>
<ul>
<li class="chapter" data-level="21.3.1" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#fórmula-geral-para-dados-não-pareados-amostras-independentes"><i class="fa fa-check"></i><b>21.3.1</b> Fórmula Geral para Dados Não Pareados (Amostras Independentes)</a></li>
<li class="chapter" data-level="21.3.2" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#fórmula-para-dados-pareados-amostras-dependentes"><i class="fa fa-check"></i><b>21.3.2</b> Fórmula para Dados Pareados (Amostras Dependentes)</a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#exemplos-práticos"><i class="fa fa-check"></i><b>21.4</b> Exemplos práticos</a>
<ul>
<li class="chapter" data-level="21.4.1" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#medicina-comparação-de-dois-tratamentos-para-dor"><i class="fa fa-check"></i><b>21.4.1</b> Medicina: Comparação de dois tratamentos para dor</a></li>
<li class="chapter" data-level="21.4.2" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#psicologia-intervenção-para-redução-de-ansiedade"><i class="fa fa-check"></i><b>21.4.2</b> Psicologia: Intervenção para redução de ansiedade</a></li>
<li class="chapter" data-level="21.4.3" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#educação-física-efeito-de-um-programa-de-treinamento-na-performance-de-corrida"><i class="fa fa-check"></i><b>21.4.3</b> Educação Física: Efeito de um programa de treinamento na performance de corrida</a></li>
</ul></li>
<li class="chapter" data-level="21.5" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#como-calcular-o-poder-do-teste-quando-você-já-tem-o-tamanho-da-amostra"><i class="fa fa-check"></i><b>21.5</b> Como calcular o poder do teste quando você já tem o tamanho da amostra</a>
<ul>
<li class="chapter" data-level="21.5.1" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#exemplo"><i class="fa fa-check"></i><b>21.5.1</b> Exemplo</a></li>
</ul></li>
<li class="chapter" data-level="21.6" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#cálculo-do-tamanho-da-amostra-para-testes-t-pareado-e-wilcoxon"><i class="fa fa-check"></i><b>21.6</b> Cálculo do Tamanho da Amostra para Testes t Pareado e Wilcoxon</a>
<ul>
<li class="chapter" data-level="21.6.1" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#teste-t-pareado-1"><i class="fa fa-check"></i><b>21.6.1</b> Teste t Pareado</a></li>
<li class="chapter" data-level="21.6.2" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#teste-de-wilcoxon-para-amostras-não-pareadas"><i class="fa fa-check"></i><b>21.6.2</b> Teste de Wilcoxon para Amostras Não Pareadas</a></li>
<li class="chapter" data-level="21.6.3" data-path="cálculo-amostral-no-r.html"><a href="cálculo-amostral-no-r.html#teste-de-wilcoxon-pareado"><i class="fa fa-check"></i><b>21.6.3</b> Teste de Wilcoxon Pareado</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="22" data-path="memes-de-estatística-p-valor.html"><a href="memes-de-estatística-p-valor.html"><i class="fa fa-check"></i><b>22</b> Memes de Estatística: p-valor</a>
<ul>
<li class="chapter" data-level="22.1" data-path="memes-de-estatística-p-valor.html"><a href="memes-de-estatística-p-valor.html#quando-você-encontra-um-p-valor-baixo-e-sabe-que-deve-rejeitar-h0"><i class="fa fa-check"></i><b>22.1</b> Quando você encontra um p-valor baixo e sabe que deve rejeitar H0</a></li>
<li class="chapter" data-level="22.2" data-path="memes-de-estatística-p-valor.html"><a href="memes-de-estatística-p-valor.html#homem-aranha-apontando"><i class="fa fa-check"></i><b>22.2</b> Homem-Aranha apontando</a></li>
<li class="chapter" data-level="22.3" data-path="memes-de-estatística-p-valor.html"><a href="memes-de-estatística-p-valor.html#namorado-distraído"><i class="fa fa-check"></i><b>22.3</b> Namorado distraído</a></li>
<li class="chapter" data-level="22.4" data-path="memes-de-estatística-p-valor.html"><a href="memes-de-estatística-p-valor.html#willy-wonka-e-o-p-valor-menor-que-005"><i class="fa fa-check"></i><b>22.4</b> Willy Wonka e o p-valor menor que 0,05</a></li>
<li class="chapter" data-level="22.5" data-path="memes-de-estatística-p-valor.html"><a href="memes-de-estatística-p-valor.html#cantada-nerd"><i class="fa fa-check"></i><b>22.5</b> Cantada Nerd</a></li>
<li class="chapter" data-level="22.6" data-path="memes-de-estatística-p-valor.html"><a href="memes-de-estatística-p-valor.html#p-valor-não-é-tudo"><i class="fa fa-check"></i><b>22.6</b> P-valor não é tudo</a></li>
<li class="chapter" data-level="22.7" data-path="memes-de-estatística-p-valor.html"><a href="memes-de-estatística-p-valor.html#coitado-do-tamanho-do-efeito"><i class="fa fa-check"></i><b>22.7</b> Coitado do tamanho do efeito</a></li>
<li class="chapter" data-level="22.8" data-path="memes-de-estatística-p-valor.html"><a href="memes-de-estatística-p-valor.html#senhora-estatística"><i class="fa fa-check"></i><b>22.8</b> Senhora estatística</a></li>
<li class="chapter" data-level="22.9" data-path="memes-de-estatística-p-valor.html"><a href="memes-de-estatística-p-valor.html#pobi-do-gatinho"><i class="fa fa-check"></i><b>22.9</b> Pobi do gatinho</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html"><i class="fa fa-check"></i><b>23</b> Pacotes <code>pwr</code>, <code>rstatix</code> e <code>effsize</code></a>
<ul>
<li class="chapter" data-level="23.1" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#cálculos-de-tamanho-de-amostra-poder-e-efeito-com-o-pacote-pwr"><i class="fa fa-check"></i><b>23.1</b> Cálculos de tamanho de amostra, poder e efeito com o pacote <code>pwr</code></a>
<ul>
<li class="chapter" data-level="23.1.1" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#exercício-1-tamanho-da-amostra-para-teste-t-não-pareado"><i class="fa fa-check"></i><b>23.1.1</b> Exercício 1: Tamanho da amostra para teste t não pareado</a></li>
<li class="chapter" data-level="23.1.2" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#exercício-2-poder-do-teste-t-não-pareado-para-n-fixo"><i class="fa fa-check"></i><b>23.1.2</b> Exercício 2: Poder do teste t não pareado para n fixo</a></li>
<li class="chapter" data-level="23.1.3" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#exercício-3-menor-efeito-detectável-no-teste-t-não-pareado"><i class="fa fa-check"></i><b>23.1.3</b> Exercício 3: Menor efeito detectável no teste t não pareado</a></li>
<li class="chapter" data-level="23.1.4" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#exercício-4-repita-para-outros-testes"><i class="fa fa-check"></i><b>23.1.4</b> Exercício 4: Repita para outros testes</a></li>
<li class="chapter" data-level="23.1.5" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#argumentos-principais-da-função-pwr.t.test"><i class="fa fa-check"></i><b>23.1.5</b> Argumentos principais da função <code>pwr.t.test()</code></a></li>
<li class="chapter" data-level="23.1.6" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#grupos-desbalanceados-usando-pwr.t2n.test"><i class="fa fa-check"></i><b>23.1.6</b> Grupos Desbalanceados: usando <code>pwr.t2n.test()</code></a></li>
</ul></li>
<li class="chapter" data-level="23.2" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#tamanho-do-efeito-em-testes-de-wilcoxon"><i class="fa fa-check"></i><b>23.2</b> Tamanho do efeito em testes de Wilcoxon</a>
<ul>
<li class="chapter" data-level="23.2.1" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#por-que-não-usar-d-de-cohen-no-wilcoxon"><i class="fa fa-check"></i><b>23.2.1</b> Por que NÃO usar d de Cohen no Wilcoxon?</a></li>
<li class="chapter" data-level="23.2.2" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#medidas-recomendadas-para-wilcoxon"><i class="fa fa-check"></i><b>23.2.2</b> Medidas recomendadas para Wilcoxon:</a></li>
<li class="chapter" data-level="23.2.3" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#comparação-entre-o-r-de-wilcoxon-e-o-delta-de-cliff"><i class="fa fa-check"></i><b>23.2.3</b> Comparação entre o r de Wilcoxon e o Delta de Cliff</a></li>
<li class="chapter" data-level="23.2.4" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#r-de-wilcoxon"><i class="fa fa-check"></i><b>23.2.4</b> r de Wilcoxon</a></li>
<li class="chapter" data-level="23.2.5" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#delta-de-cliff-delta"><i class="fa fa-check"></i><b>23.2.5</b> Delta de Cliff (<span class="math inline">\(\delta\)</span>)</a></li>
<li class="chapter" data-level="23.2.6" data-path="pacotes-pwr-rstatix-e-effsize.html"><a href="pacotes-pwr-rstatix-e-effsize.html#qual-é-melhor-usar"><i class="fa fa-check"></i><b>23.2.6</b> Qual é melhor usar?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="24" data-path="teste-de-normalidade.html"><a href="teste-de-normalidade.html"><i class="fa fa-check"></i><b>24</b> Teste de Normalidade</a>
<ul>
<li class="chapter" data-level="24.1" data-path="teste-de-normalidade.html"><a href="teste-de-normalidade.html#hipóteses-nos-testes-de-normalidade"><i class="fa fa-check"></i><b>24.1</b> Hipóteses nos Testes de Normalidade</a></li>
<li class="chapter" data-level="24.2" data-path="teste-de-normalidade.html"><a href="teste-de-normalidade.html#principais-testes-de-normalidade"><i class="fa fa-check"></i><b>24.2</b> Principais Testes de Normalidade</a>
<ul>
<li class="chapter" data-level="24.2.1" data-path="teste-de-normalidade.html"><a href="teste-de-normalidade.html#dicas-de-uso"><i class="fa fa-check"></i><b>24.2.1</b> Dicas de Uso</a></li>
<li class="chapter" data-level="24.2.2" data-path="teste-de-normalidade.html"><a href="teste-de-normalidade.html#exemplo-prático-em-r-2"><i class="fa fa-check"></i><b>24.2.2</b> Exemplo Prático em R</a></li>
</ul></li>
<li class="chapter" data-level="24.3" data-path="teste-de-normalidade.html"><a href="teste-de-normalidade.html#assimetria-e-curtose-o-que-são-e-por-que-são-importantes"><i class="fa fa-check"></i><b>24.3</b> Assimetria e Curtose: O que são e por que são importantes?</a>
<ul>
<li class="chapter" data-level="24.3.1" data-path="teste-de-normalidade.html"><a href="teste-de-normalidade.html#o-que-é-assimetria-skewness"><i class="fa fa-check"></i><b>24.3.1</b> O que é Assimetria (Skewness)?</a></li>
<li class="chapter" data-level="24.3.2" data-path="teste-de-normalidade.html"><a href="teste-de-normalidade.html#o-que-é-curtose-kurtosis"><i class="fa fa-check"></i><b>24.3.2</b> O que é Curtose (Kurtosis)?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="25" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html"><i class="fa fa-check"></i><b>25</b> Comparação de mais de dois grupos</a>
<ul>
<li class="chapter" data-level="25.1" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#revisando-as-hipóteses-da-comparação-entre-dois-grupos"><i class="fa fa-check"></i><b>25.1</b> Revisando as hipóteses da comparação entre dois grupos</a></li>
<li class="chapter" data-level="25.2" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#hipóteses-para-a-comparação-entre-mais-de-dois-grupos"><i class="fa fa-check"></i><b>25.2</b> Hipóteses para a comparação entre mais de dois grupos</a></li>
<li class="chapter" data-level="25.3" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#testes-paramétricos"><i class="fa fa-check"></i><b>25.3</b> Testes Paramétricos</a>
<ul>
<li class="chapter" data-level="25.3.1" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#pré-requisitos-para-anova-dados-pareados-ou-não"><i class="fa fa-check"></i><b>25.3.1</b> Pré-requisitos para ANOVA (dados pareados ou não)</a></li>
</ul></li>
<li class="chapter" data-level="25.4" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#testes-não-paramétricos"><i class="fa fa-check"></i><b>25.4</b> Testes Não Paramétricos</a></li>
<li class="chapter" data-level="25.5" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#anova-de-uma-via-no-r"><i class="fa fa-check"></i><b>25.5</b> ANOVA de uma via no R</a>
<ul>
<li class="chapter" data-level="25.5.1" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#simulação-de-dados"><i class="fa fa-check"></i><b>25.5.1</b> Simulação de Dados</a></li>
<li class="chapter" data-level="25.5.2" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#visualização-dos-dados"><i class="fa fa-check"></i><b>25.5.2</b> Visualização dos Dados</a></li>
<li class="chapter" data-level="25.5.3" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#verificação-dos-pré-requisitos-para-anova"><i class="fa fa-check"></i><b>25.5.3</b> Verificação dos Pré-requisitos para ANOVA</a></li>
<li class="chapter" data-level="25.5.4" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#anova-de-uma-via"><i class="fa fa-check"></i><b>25.5.4</b> ANOVA de Uma Via</a></li>
</ul></li>
<li class="chapter" data-level="25.6" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#kruskal-wallis-no-r"><i class="fa fa-check"></i><b>25.6</b> Kruskal-Wallis no R</a>
<ul>
<li class="chapter" data-level="25.6.1" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#teste-post-hoc-para-kruskal-wallis"><i class="fa fa-check"></i><b>25.6.1</b> Teste Post Hoc para Kruskal-Wallis</a></li>
</ul></li>
<li class="chapter" data-level="25.7" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#por-que-não-é-indicado-comparar-os-grupos-dois-a-dois-diretamente"><i class="fa fa-check"></i><b>25.7</b> Por que não é indicado comparar os grupos dois a dois diretamente?</a></li>
<li class="chapter" data-level="25.8" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#anova-para-dados-repetidos-no-r"><i class="fa fa-check"></i><b>25.8</b> ANOVA para Dados Repetidos no R</a>
<ul>
<li class="chapter" data-level="25.8.1" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#gerar-dados-simulados"><i class="fa fa-check"></i><b>25.8.1</b> Gerar dados simulados</a></li>
<li class="chapter" data-level="25.8.2" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#converter-para-formato-longo"><i class="fa fa-check"></i><b>25.8.2</b> Converter para formato longo</a></li>
<li class="chapter" data-level="25.8.3" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#visualização-opcional"><i class="fa fa-check"></i><b>25.8.3</b> Visualização (opcional)</a></li>
<li class="chapter" data-level="25.8.4" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#teste-de-normalidade-das-diferenças-pré-requisito"><i class="fa fa-check"></i><b>25.8.4</b> Teste de normalidade das diferenças (pré-requisito)</a></li>
<li class="chapter" data-level="25.8.5" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#anova-de-medidas-repetidas-com-afex-testa-e-corrige-esfericidade"><i class="fa fa-check"></i><b>25.8.5</b> ANOVA de medidas repetidas com afex (testa e corrige esfericidade)</a></li>
<li class="chapter" data-level="25.8.6" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#pós-hoc-comparações-múltiplas-entre-as-provas"><i class="fa fa-check"></i><b>25.8.6</b> Pós-hoc: Comparações múltiplas entre as provas</a></li>
</ul></li>
<li class="chapter" data-level="25.9" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#teste-de-friedman"><i class="fa fa-check"></i><b>25.9</b> Teste de Friedman</a>
<ul>
<li class="chapter" data-level="25.9.1" data-path="comparação-de-mais-de-dois-grupos.html"><a href="comparação-de-mais-de-dois-grupos.html#pós-teste-comparações-múltiplas-wilcoxon-pareado"><i class="fa fa-check"></i><b>25.9.1</b> Pós-teste: Comparações Múltiplas (Wilcoxon pareado)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html"><i class="fa fa-check"></i><b>26</b> Correlação entre variáveis</a>
<ul>
<li class="chapter" data-level="26.1" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#tipos-de-variáveis-1"><i class="fa fa-check"></i><b>26.1</b> Tipos de Variáveis</a></li>
<li class="chapter" data-level="26.2" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#diagrama-de-dispersão"><i class="fa fa-check"></i><b>26.2</b> Diagrama de Dispersão</a></li>
<li class="chapter" data-level="26.3" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#coeficientes-de-correlação"><i class="fa fa-check"></i><b>26.3</b> Coeficientes de Correlação</a>
<ul>
<li class="chapter" data-level="26.3.1" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#coeficiente-de-correlação-de-pearson"><i class="fa fa-check"></i><b>26.3.1</b> Coeficiente de Correlação de Pearson</a></li>
<li class="chapter" data-level="26.3.2" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#coeficiente-de-correlação-de-spearman"><i class="fa fa-check"></i><b>26.3.2</b> Coeficiente de Correlação de Spearman</a></li>
<li class="chapter" data-level="26.3.3" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#coeficiente-de-correlação-de-kendall"><i class="fa fa-check"></i><b>26.3.3</b> Coeficiente de Correlação de Kendall</a></li>
<li class="chapter" data-level="26.3.4" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#interpretação-dos-coeficientes"><i class="fa fa-check"></i><b>26.3.4</b> Interpretação dos Coeficientes</a></li>
<li class="chapter" data-level="26.3.5" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#exemplo-no-r"><i class="fa fa-check"></i><b>26.3.5</b> Exemplo no R</a></li>
</ul></li>
<li class="chapter" data-level="26.4" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#testes-de-correlação"><i class="fa fa-check"></i><b>26.4</b> Testes de Correlação</a>
<ul>
<li class="chapter" data-level="26.4.1" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#pearson"><i class="fa fa-check"></i><b>26.4.1</b> Pearson</a></li>
<li class="chapter" data-level="26.4.2" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#spearman"><i class="fa fa-check"></i><b>26.4.2</b> Spearman</a></li>
<li class="chapter" data-level="26.4.3" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#kendall"><i class="fa fa-check"></i><b>26.4.3</b> Kendall</a></li>
</ul></li>
<li class="chapter" data-level="26.5" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#tamanho-do-efeito-effect-size"><i class="fa fa-check"></i><b>26.5</b> Tamanho do Efeito (Effect Size)</a></li>
<li class="chapter" data-level="26.6" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#cálculo-do-tamanho-da-amostra-e-poder-estatístico"><i class="fa fa-check"></i><b>26.6</b> Cálculo do Tamanho da Amostra e Poder Estatístico</a>
<ul>
<li class="chapter" data-level="26.6.1" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#exemplo-com-pwr"><i class="fa fa-check"></i><b>26.6.1</b> Exemplo com <code>pwr</code></a></li>
<li class="chapter" data-level="26.6.2" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#verificar-o-poder-para-uma-amostra-de-tamanho-30"><i class="fa fa-check"></i><b>26.6.2</b> Verificar o poder para uma amostra de tamanho 30:</a></li>
</ul></li>
<li class="chapter" data-level="26.7" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#outros-recursos"><i class="fa fa-check"></i><b>26.7</b> Outros recursos</a>
<ul>
<li class="chapter" data-level="26.7.1" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#visualização-com-pairs"><i class="fa fa-check"></i><b>26.7.1</b> Visualização com <code>pairs()</code></a></li>
<li class="chapter" data-level="26.7.2" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#matriz-de-correlação-com-cor"><i class="fa fa-check"></i><b>26.7.2</b> Matriz de Correlação com <code>cor()</code></a></li>
<li class="chapter" data-level="26.7.3" data-path="correlação-entre-variáveis.html"><a href="correlação-entre-variáveis.html#matriz-visual-com-ggallyggcorr"><i class="fa fa-check"></i><b>26.7.3</b> Matriz Visual com <code>GGally::ggcorr()</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="27" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html"><i class="fa fa-check"></i><b>27</b> Associação entre variáveis</a>
<ul>
<li class="chapter" data-level="27.1" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#tipos-de-variáveis-envolvidas"><i class="fa fa-check"></i><b>27.1</b> Tipos de Variáveis Envolvidas</a></li>
<li class="chapter" data-level="27.2" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#tabela-de-contingência"><i class="fa fa-check"></i><b>27.2</b> Tabela de Contingência</a>
<ul>
<li class="chapter" data-level="27.2.1" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#cálculo-das-frequências-esperadas"><i class="fa fa-check"></i><b>27.2.1</b> Cálculo das Frequências Esperadas</a></li>
</ul></li>
<li class="chapter" data-level="27.3" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#principais-testes-de-associação"><i class="fa fa-check"></i><b>27.3</b> Principais Testes de Associação</a>
<ul>
<li class="chapter" data-level="27.3.1" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#exemplos"><i class="fa fa-check"></i><b>27.3.1</b> Exemplos</a></li>
<li class="chapter" data-level="27.3.2" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#teste-qui-quadrado"><i class="fa fa-check"></i><b>27.3.2</b> Teste Qui-Quadrado</a></li>
<li class="chapter" data-level="27.3.3" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#teste-exato-de-fisher"><i class="fa fa-check"></i><b>27.3.3</b> Teste Exato de Fisher</a></li>
<li class="chapter" data-level="27.3.4" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#exemplo-no-r-1"><i class="fa fa-check"></i><b>27.3.4</b> Exemplo no R</a></li>
<li class="chapter" data-level="27.3.5" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#observação-sobre-tabelas-de-contingência-em-artigos-científicos"><i class="fa fa-check"></i><b>27.3.5</b> Observação sobre tabelas de contingência em artigos científicos</a></li>
</ul></li>
<li class="chapter" data-level="27.4" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#tamanho-do-efeito-medidas-de-associação"><i class="fa fa-check"></i><b>27.4</b> Tamanho do Efeito: Medidas de Associação</a>
<ul>
<li class="chapter" data-level="27.4.1" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#v-de-cramer"><i class="fa fa-check"></i><b>27.4.1</b> V de Cramer</a></li>
<li class="chapter" data-level="27.4.2" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#phi-de-pearson-phi"><i class="fa fa-check"></i><b>27.4.2</b> Phi de Pearson <span class="math inline">\((\phi)\)</span></a></li>
<li class="chapter" data-level="27.4.3" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#odds-ratio-razão-de-chances"><i class="fa fa-check"></i><b>27.4.3</b> Odds Ratio (Razão de Chances)</a></li>
</ul></li>
<li class="chapter" data-level="27.5" data-path="associação-entre-variáveis.html"><a href="associação-entre-variáveis.html#cálculo-do-poder-estatístico"><i class="fa fa-check"></i><b>27.5</b> Cálculo do Poder Estatístico</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="referências.html"><a href="referências.html"><i class="fa fa-check"></i>Referências</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado com bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estatística + R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="comparação-entre-dois-grupos" class="section level1 hasAnchor" number="20">
<h1><span class="header-section-number">Capítulo 20</span> Comparação entre dois grupos<a href="comparação-entre-dois-grupos.html#comparação-entre-dois-grupos" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>O fluxograma abaixo apresenta a sequência de etapas para a escolha do teste estatístico mais adequado na comparação entre dois grupos, considerando o tipo de comparação entre os dois grupos (pareada ou não pareada) e a verificação da normalidade dos dados.</p>
<div class="grViz html-widget html-fill-item" id="htmlwidget-30e4409849e39179307f" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-30e4409849e39179307f">{"x":{"diagram":"\ndigraph fluxo_teste {\n  graph [layout = dot, rankdir = TB, bgcolor = white]\n\n  node [shape = box, style = solid, fontname = \"Arial\"]\n  grupos2      [label = \"2 grupos\"]\n  pareados     [label = \"Pareados\"]\n  naopareados  [label = \"Não Pareados\"]\n  norm_p       [label = \"Normalidade?\"]\n  p_sim        [label = \"Teste t\"]\n  p_nao        [label = \"Teste Wilcoxon\"]\n  norm_np      [label = \"Normalidade?\"]\n  variancia    [label = \"Teste de variância\"]\n  t_indep      [label = \"Teste t\"]\n  wmw_indep    [label = \"Teste Wilcoxon\"]\n\n  # Círculos para Sim/Não\n  sim1         [label = \"Sim\", shape = circle, width = 0.2, style = solid]\n  nao1         [label = \"Não\", shape = circle, width = 0.2, style = solid]\n  sim2         [label = \"Sim\", shape = circle, width = 0.2, style = solid]\n  nao2         [label = \"Não\", shape = circle, width = 0.2, style = solid]\n\n  grupos2      -> pareados\n  grupos2      -> naopareados\n\n  pareados     -> norm_p\n  norm_p       -> sim1\n  norm_p       -> nao1\n  sim1         -> p_sim\n  nao1         -> p_nao\n\n  naopareados  -> norm_np\n  norm_np      -> sim2\n  norm_np      -> nao2\n  sim2         -> variancia\n  variancia    -> t_indep\n  nao2         -> wmw_indep\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
<p>Exemplos didáticos para comparação entre dois grupos são mostrados a seguir.</p>
<div id="teste-t-pareado" class="section level2 hasAnchor" number="20.1">
<h2><span class="header-section-number">20.1</span> Teste t pareado<a href="comparação-entre-dois-grupos.html#teste-t-pareado" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O teste t (pareado ou não pareado) é um teste <strong>paramétrico</strong>, por isso, antes de aplicar o teste, recomenda-se verificar a normalidade dos dados.</p>
<p>O teste t pareado avalia se há diferença entre as médias de dois conjuntos dependentes (ex: antes e depois em um mesmo grupo).</p>
<p><strong>Hipóteses:</strong></p>
<blockquote>
<p>H₀: A média antes é igual à média depois (não há efeito).</p>
</blockquote>
<blockquote>
<p>H₁: A média antes é diferente da média depois (há efeito).</p>
</blockquote>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="comparação-entre-dois-grupos.html#cb89-1" tabindex="-1"></a><span class="co"># Simulando dados: pressão antes e depois</span></span>
<span id="cb89-2"><a href="comparação-entre-dois-grupos.html#cb89-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb89-3"><a href="comparação-entre-dois-grupos.html#cb89-3" tabindex="-1"></a>antes <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="at">mean=</span><span class="dv">120</span>, <span class="at">sd=</span><span class="dv">10</span>)</span>
<span id="cb89-4"><a href="comparação-entre-dois-grupos.html#cb89-4" tabindex="-1"></a>depois <span class="ot">&lt;-</span> antes <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="at">mean=</span><span class="sc">-</span><span class="dv">5</span>, <span class="at">sd=</span><span class="dv">8</span>) <span class="co"># espera-se uma redução média de 5</span></span>
<span id="cb89-5"><a href="comparação-entre-dois-grupos.html#cb89-5" tabindex="-1"></a></span>
<span id="cb89-6"><a href="comparação-entre-dois-grupos.html#cb89-6" tabindex="-1"></a><span class="co"># Teste t pareado</span></span>
<span id="cb89-7"><a href="comparação-entre-dois-grupos.html#cb89-7" tabindex="-1"></a><span class="fu">t.test</span>(antes, depois, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  antes and depois
## t = 3.644, df = 19, p-value = 0.001726
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  2.302671 8.517443
## sample estimates:
## mean difference 
##        5.410057</code></pre>
<p>No R, fazer o teste t pareado é muito fácil. Você só precisa usar uma linha: <code>t.test(antes, depois, paired = TRUE)</code>.</p>
<p>Basta colocar os seus dois conjuntos de dados (por exemplo, as medidas antes e depois) e escrever <strong><code>paired = TRUE</code></strong> para avisar ao R que os dados são do mesmo grupo em dois momentos.</p>
<p>Assim, o R faz todo o cálculo para você!</p>
<p>Ao realizar o teste t pareado no R, a saída apresenta várias informações importantes:</p>
<ul>
<li><strong>t</strong>: Este é o valor do teste t calculado a partir dos dados. Ele indica o quanto a diferença média observada entre os grupos se afasta do que seria esperado se não houvesse diferença real.</li>
<li><strong>df</strong>: Significa “degrees of freedom” (graus de liberdade), que neste caso é igual ao número de pares menos 1 (aqui, 19).</li>
<li><strong>p-value</strong>: É a probabilidade de observarmos uma diferença igual ou maior que a encontrada, caso a hipótese nula (de que não há diferença) seja verdadeira. Um p-valor pequeno (por exemplo, menor que 0,05) indica que a diferença é estatisticamente significativa.</li>
<li><strong>alternative hypothesis</strong>: Mostra qual hipótese alternativa está sendo testada – neste caso, que a diferença média entre “antes” e “depois” é diferente de zero.</li>
<li><strong>95 percent confidence interval</strong>: Indica o intervalo de valores no qual a verdadeira diferença média está com 95% de confiança. Aqui, podemos dizer que a diferença média entre os grupos está provavelmente entre 2,30 e 8,52.</li>
<li><strong>mean difference</strong>: É a diferença média observada nos dados, neste exemplo, aproximadamente 5,41.</li>
</ul>
<p><strong>Resumo:</strong></p>
<p>O resultado sugere que há uma diferença significativa entre “antes” e “depois” (p = 0,0017), com a diferença média estimada em 5,41 unidades e um intervalo de confiança que não inclui zero.</p>
<blockquote>
<p><strong>Observação</strong>: Se p é maior que 0,05, não rejeitamos H₀, nesse caso a conclusão seria que não há evidência de diferença significativa.</p>
</blockquote>
</div>
<div id="wilcoxon-pareado" class="section level2 hasAnchor" number="20.2">
<h2><span class="header-section-number">20.2</span> Wilcoxon pareado<a href="comparação-entre-dois-grupos.html#wilcoxon-pareado" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O teste de Wilcoxon para amostras pareadas é a alternativa não paramétrica ao teste t pareado, sendo utilizado quando os dados não seguem uma distribuição normal.</p>
<p><strong>Hipóteses:</strong></p>
<blockquote>
<p>H₀: As distribuições dos pares são iguais (não há diferença entre antes e depois).</p>
</blockquote>
<blockquote>
<p>H₁: As distribuições dos pares são diferentes (há diferença entre antes e depois).</p>
</blockquote>
<p>Formalmente, o teste verifica se a <strong>distribuição das diferenças entre os pares</strong> é simétrica em torno de zero. Quando essa condição de simetria é atendida, podemos interpretar o teste como uma comparação das <strong>medianas</strong> das duas situações (por exemplo, antes e depois).</p>
<p><strong>Hipóteses:</strong></p>
<blockquote>
<p>H₀: A mediana das diferenças entre os pares é igual a zero (não há diferença entre antes e depois).</p>
</blockquote>
<blockquote>
<p>H₁: A mediana das diferenças entre os pares é diferente de zero (há diferença entre antes e depois).</p>
</blockquote>
<p><em>Observação: Esta formulação das hipóteses em termos de mediana é válida quando as diferenças apresentam distribuição simétrica.</em></p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="comparação-entre-dois-grupos.html#cb91-1" tabindex="-1"></a><span class="fu">wilcox.test</span>(antes, depois, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  antes and depois
## V = 179, p-value = 0.004221
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Ao fazer o teste de Wilcoxon pareado no R, a resposta traz as seguintes informações:</p>
<ul>
<li><strong>V</strong>: É o valor da estatística do teste de Wilcoxon, calculado a partir das diferenças entre os pares. Não precisamos interpretar esse número diretamente; ele serve para o cálculo do p-valor.</li>
<li><strong>p-value</strong>: É a chance de observarmos uma diferença igual ou maior que a encontrada, caso não exista diferença real entre os grupos. Se o p-valor for menor que 0,05, dizemos que há diferença significativa entre “antes” e “depois”.</li>
<li><strong>alternative hypothesis</strong>: Mostra qual hipótese alternativa foi testada. Nesse caso, que a posição central (mediana) dos dois momentos não é igual.</li>
</ul>
<p>No R, por padrão, a função <code>wilcox.test()</code> não mostra o intervalo de confiança para a mediana das diferenças.
No entanto, você pode pedir para calcular o intervalo de confiança usando o argumento <strong><code>conf.int = TRUE</code></strong>:</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="comparação-entre-dois-grupos.html#cb93-1" tabindex="-1"></a><span class="fu">wilcox.test</span>(antes, depois, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  antes and depois
## V = 179, p-value = 0.004221
## alternative hypothesis: true location shift is not equal to 0
## 95 percent confidence interval:
##  2.291397 8.680443
## sample estimates:
## (pseudo)median 
##       5.545154</code></pre>
<p>Observações sobre o intervalo de confiança do teste de Wilcoxon</p>
<p><strong>95 percent confidence interval:</strong><br />
O intervalo de confiança de 95% vai de 2,29 até 8,68. Isso significa que, com 95% de confiança, a verdadeira mediana da diferença entre “antes” e “depois” está entre esses valores.<br />
Como esse intervalo <strong>não inclui o zero</strong>, temos mais uma indicação de que existe diferença significativa entre os dois momentos.</p>
<p><strong>(pseudo)median:</strong><br />
O valor de 5,55 indica a mediana das diferenças observadas nos dados.<br />
É chamado de “pseudo-median” porque, no teste de Wilcoxon, esse valor é uma estimativa robusta do deslocamento central entre os pares.</p>
<p>O termo “pseudo-median” aparece no teste de Wilcoxon porque, nesse teste, a maneira de calcular a “mediana” é um pouco diferente da mediana comum.</p>
<p><strong>Mediana comum:</strong> É o valor do meio quando colocamos todos os números em ordem.</p>
<p><strong>Pseudo-median:</strong> No teste de Wilcoxon, em vez de pegar só o valor do meio, o cálculo usa todos os pares possíveis de diferenças entre os grupos. Ele faz uma média especial desses valores do meio. Por isso, chama-se “pseudo” (uma “falsa” ou “quase” mediana).</p>
</div>
<div id="teste-t-não-pareado" class="section level2 hasAnchor" number="20.3">
<h2><span class="header-section-number">20.3</span> Teste t não pareado<a href="comparação-entre-dois-grupos.html#teste-t-não-pareado" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Se você olhar no fluxograma apresentado no início do capítulo, você verá que antes de executar o teste t para amostras não pareadas, é necessário executar o teste de variância.</p>
<div id="teste-de-variância" class="section level3 hasAnchor" number="20.3.1">
<h3><span class="header-section-number">20.3.1</span> Teste de variância<a href="comparação-entre-dois-grupos.html#teste-de-variância" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>É um pré-requisito para o teste t não pareado</strong> Verifica se as variâncias de dois grupos não pareados podem ser consideradas iguais ou não.</p>
<p><strong>Hipóteses:</strong></p>
<blockquote>
<p>H₀: As variâncias dos dois grupos são iguais.</p>
</blockquote>
<blockquote>
<p>H₁: As variâncias dos dois grupos são diferentes.</p>
</blockquote>
<p><strong>Interpretação:</strong></p>
<p>Se p &lt; 0,05, rejeitamos H₀ e concluímos que as variâncias são diferentes</p>
<blockquote>
<p>No teste t acrescentado o argumento <code>var.equal=FALSE</code> ou <code>var.equal=F</code>.</p>
</blockquote>
<p>Se p &gt; 0,05, consideramos as variâncias iguais.</p>
<blockquote>
<p>No teste t acrescentado o argumento <code>var.equal=TRUE</code> ou <code>var.equal=T</code></p>
</blockquote>
<p><strong>Importante:</strong></p>
<p>O argumento <strong><code>var.equal</code></strong> dentro de <strong><code>t.test()</code></strong> define qual versão do teste será utilizada: se <code>var.equal = TRUE</code>, o teste assume variâncias iguais; se <code>var.equal = FALSE</code>, é usada a correção de Welch, que não assume homogeneidade. A escolha incorreta desse parâmetro pode comprometer a validade do p-valor obtido, afetando a conclusão do teste.</p>
<p><strong>Explicação didática</strong></p>
<p>Imagine que você quer comparar as médias de duas turmas. A Turma A tem poucos alunos e notas parecidas; a Turma B tem muitos alunos, mas as notas variam bastante.</p>
<p>Se você comparar as médias assumindo que ambas têm a mesma variação, o resultado pode ser injusto.</p>
<p>A correção de Welch resolve isso: ela ajusta o cálculo do teste para considerar que as turmas são diferentes — olhando para a variação e o tamanho de cada grupo separadamente. Assim, o teste fica mais confiável quando os grupos são desiguais.</p>
<hr />
<p>O teste t para amostras não pareadas compara médias de dois grupos independentes.</p>
<p><strong>Hipóteses:</strong></p>
<blockquote>
<p>H₀: A média do grupo A é igual à média do grupo B.</p>
</blockquote>
<blockquote>
<p>H₁: As médias dos grupos são diferentes.</p>
</blockquote>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="comparação-entre-dois-grupos.html#cb95-1" tabindex="-1"></a><span class="co"># Simulando dados</span></span>
<span id="cb95-2"><a href="comparação-entre-dois-grupos.html#cb95-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">456</span>)</span>
<span id="cb95-3"><a href="comparação-entre-dois-grupos.html#cb95-3" tabindex="-1"></a>grupoA <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean=</span><span class="dv">50</span>, <span class="at">sd=</span><span class="dv">7</span>)</span>
<span id="cb95-4"><a href="comparação-entre-dois-grupos.html#cb95-4" tabindex="-1"></a>grupoB <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean=</span><span class="dv">55</span>, <span class="at">sd=</span><span class="dv">7</span>)</span>
<span id="cb95-5"><a href="comparação-entre-dois-grupos.html#cb95-5" tabindex="-1"></a></span>
<span id="cb95-6"><a href="comparação-entre-dois-grupos.html#cb95-6" tabindex="-1"></a><span class="co"># Teste de variância (pré-requisito do t independente)</span></span>
<span id="cb95-7"><a href="comparação-entre-dois-grupos.html#cb95-7" tabindex="-1"></a><span class="fu">var.test</span>(grupoA, grupoB)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  grupoA and grupoB
## F = 1.8842, num df = 29, denom df = 29, p-value = 0.09347
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.896797 3.958627
## sample estimates:
## ratio of variances 
##           1.884167</code></pre>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="comparação-entre-dois-grupos.html#cb97-1" tabindex="-1"></a><span class="co"># Teste t independente</span></span>
<span id="cb97-2"><a href="comparação-entre-dois-grupos.html#cb97-2" tabindex="-1"></a><span class="fu">t.test</span>(grupoA, grupoB, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  grupoA and grupoB
## t = -2.4453, df = 58, p-value = 0.01753
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -8.1306016 -0.8110054
## sample estimates:
## mean of x mean of y 
##   51.6222   56.0930</code></pre>
<p><strong>Descrição dos resultados do teste F para comparação de variâncias</strong></p>
<ul>
<li><strong>F = 1.8842</strong>: Este é o valor da estatística F, que compara as duas variâncias. Ele é calculado dividindo a variância do grupo com maior variância pela variância do outro grupo.</li>
<li><strong>num df = 29, denom df = 29</strong>: Esses são os graus de liberdade, relacionados ao tamanho de cada grupo (n - 1), neste caso ambos com 30 participantes.</li>
<li><strong>p-value = 0.09347</strong>: Este é o valor de significância. Ele mostra a probabilidade de observarmos uma diferença entre as variâncias tão grande quanto a encontrada, caso as variâncias dos grupos fossem realmente iguais. Como o p-valor é maior que 0,05, não podemos dizer que as variâncias são diferentes de forma significativa.</li>
<li><strong>alternative hypothesis: true ratio of variances is not equal to 1</strong>: Isso mostra que o teste está verificando se as variâncias são diferentes (não iguais).</li>
<li><strong>95 percent confidence interval: 0.896797 a 3.958627</strong>: Com 95% de confiança, o verdadeiro valor da razão entre as variâncias está entre aproximadamente 0,90 e 3,96. Como esse intervalo inclui o valor 1, não há diferença significativa entre as variâncias.</li>
<li><strong>ratio of variances = 1.884167</strong>: Esse é o valor observado da razão entre as variâncias dos dois grupos. O grupo com maior variância tem uma variância cerca de 1,88 vezes maior que o outro grupo.</li>
</ul>
<p><strong>Resumo:</strong><br />
O teste F mostrou que não há diferença estatisticamente significativa entre as variâncias dos grupos A e B, pois o p-valor é maior que 0,05 e o intervalo de confiança inclui o valor 1.</p>
<p><strong>Descrição dos resultados do teste t para duas amostras não pareadas</strong></p>
<ul>
<li><strong>t = -2.4453</strong>: Este é o valor da estatística t, que indica o quanto as médias dos grupos A e B diferem em relação à variação dos dados.</li>
<li><strong>df = 58</strong>: São os graus de liberdade do teste, relacionados ao tamanho das amostras.</li>
<li><strong>p-value = 0.01753</strong>: O p-valor representa a probabilidade de encontrar uma diferença igual ou maior que a observada entre as médias, caso realmente não haja diferença entre os grupos. Como o p-valor é menor que 0,05, podemos considerar que há diferença estatisticamente significativa entre as médias de grupoA e grupoB.</li>
<li><strong>alternative hypothesis: true difference in means is not equal to 0</strong>: O teste verifica se existe diferença entre as médias dos dois grupos (hipótese alternativa de diferença).</li>
<li><strong>95 percent confidence interval: -8.13 a -0.81</strong>: Com 95% de confiança, a diferença real entre as médias está entre -8,13 e -0,81. Como esse intervalo não inclui o zero, reforça a indicação de diferença significativa.</li>
<li><strong>mean of x (grupoA): 51.62</strong><br />
<strong>mean of y (grupoB): 56.09</strong><br />
As médias dos grupos mostram que o grupo B teve, em média, um valor maior que o grupo A.</li>
</ul>
<p><strong>Resumo:</strong><br />
O teste t indicou que existe uma diferença estatisticamente significativa entre as médias dos grupos A e B. O grupo B apresentou média maior que o grupo A, e essa diferença dificilmente ocorreu ao acaso.</p>
</div>
</div>
<div id="wilcoxon-não-pareado" class="section level2 hasAnchor" number="20.4">
<h2><span class="header-section-number">20.4</span> Wilcoxon não pareado<a href="comparação-entre-dois-grupos.html#wilcoxon-não-pareado" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O teste é também conhecido como Wilcoxon-Mann-Whitney. É a alternativa não paramétrica ao t independente para comparar dois grupos independentes.</p>
<p><strong>Hipóteses:</strong></p>
<blockquote>
<p>H₀: As distribuições dos grupos são iguais.</p>
</blockquote>
<blockquote>
<p>H₁: As distribuições dos grupos são diferentes.</p>
</blockquote>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="comparação-entre-dois-grupos.html#cb99-1" tabindex="-1"></a><span class="fu">wilcox.test</span>(grupoA, grupoB)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum exact test
## 
## data:  grupoA and grupoB
## W = 316, p-value = 0.04789
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p><strong>Descrição dos resultados do teste de Wilcoxon para duas amostras não pareadas</strong></p>
<ul>
<li><strong>W = 316</strong>: Este é o valor da estatística de Wilcoxon, que representa a soma dos postos atribuídos aos valores dos grupos ao comparar suas distribuições.</li>
<li><strong>p-value = 0.04789</strong>: O valor de p indica a probabilidade de observar uma diferença igual ou maior entre os grupos, caso não exista diferença real. Como é menor que 0,05, isso sugere que há diferença estatisticamente significativa entre os grupos A e B.</li>
<li><strong>alternative hypothesis: true location shift is not equal to 0</strong>: O teste está avaliando se há diferença (deslocamento) entre as localizações centrais dos dois grupos (medianas diferentes).</li>
</ul>
<p><strong>Resumo:</strong><br />
O teste de Wilcoxon mostrou que há uma diferença estatisticamente significativa nas distribuições dos grupos A e B, indicando que eles provavelmente apresentam medianas diferentes.</p>
</div>
<div id="teste-bilateral-vs.-teste-unilateral" class="section level2 hasAnchor" number="20.5">
<h2><span class="header-section-number">20.5</span> Teste bilateral vs. teste unilateral<a href="comparação-entre-dois-grupos.html#teste-bilateral-vs.-teste-unilateral" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="o-que-são" class="section level3 hasAnchor" number="20.5.1">
<h3><span class="header-section-number">20.5.1</span> O que são?<a href="comparação-entre-dois-grupos.html#o-que-são" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><strong>Teste bilateral (bicaudal ou two-sided):</strong>
<ul>
<li>Verifica se há diferença <strong>em qualquer direção</strong> entre os grupos ou condições.</li>
<li>Exemplo: “Será que a média do grupo A é <strong>diferente</strong> da média do grupo B?” (pode ser maior ou menor).</li>
</ul></li>
<li><strong>Teste unilateral (caudal ou one-sided):</strong>
<ul>
<li>Verifica se há diferença <strong>em uma direção específica</strong>.</li>
<li>Exemplo: “Será que a média do grupo A é <strong>maior</strong> que a média do grupo B?” ou “Será que é <strong>menor</strong>?”.</li>
</ul></li>
</ul>
<hr />
</div>
<div id="formulação-das-hipóteses" class="section level3 hasAnchor" number="20.5.2">
<h3><span class="header-section-number">20.5.2</span> Formulação das hipóteses<a href="comparação-entre-dois-grupos.html#formulação-das-hipóteses" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><strong>Teste bilateral:</strong>
<ul>
<li>Hipótese nula (<span class="math inline">\(H_0\)</span>): não há diferença (<span class="math inline">\(\mu_A = \mu_B\)</span>)</li>
<li>Hipótese alternativa (<span class="math inline">\(H_1\)</span>): há diferença (<span class="math inline">\(\mu_A \neq \mu_B\)</span>)</li>
</ul></li>
<li><strong>Teste unilateral (maior):</strong>
<ul>
<li>Hipótese nula (<span class="math inline">\(H_0\)</span>): <span class="math inline">\(\mu_A \leq \mu_B\)</span></li>
<li>Hipótese alternativa (<span class="math inline">\(H_1\)</span>): <span class="math inline">\(\mu_A &gt; \mu_B\)</span></li>
</ul></li>
<li><strong>Teste unilateral (menor):</strong>
<ul>
<li>Hipótese nula (<span class="math inline">\(H_0\)</span>): <span class="math inline">\(\mu_A \geq \mu_B\)</span></li>
<li>Hipótese alternativa (<span class="math inline">\(H_1\)</span>): <span class="math inline">\(\mu_A &lt; \mu_B\)</span></li>
</ul></li>
</ul>
<hr />
</div>
<div id="influência-no-cálculo-do-p-valor" class="section level3 hasAnchor" number="20.5.3">
<h3><span class="header-section-number">20.5.3</span> Influência no cálculo do p-valor<a href="comparação-entre-dois-grupos.html#influência-no-cálculo-do-p-valor" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><strong>Teste bilateral:</strong><br />
O p-valor representa a probabilidade de encontrar um resultado tão extremo quanto o observado <strong>em ambas as direções</strong> (para mais ou para menos).<br />
É mais rigoroso, pois considera desvios para cima e para baixo.</p></li>
<li><p><strong>Teste unilateral:</strong><br />
O p-valor considera apenas <strong>uma direção</strong> (maior ou menor).<br />
Geralmente, o p-valor do teste unilateral é a metade do bilateral, para o mesmo dado e direção, tornando o teste <strong>mais sensível</strong> a detectar diferenças naquela direção, mas exige justificativa teórica para ser usado.</p></li>
</ul>
<hr />
</div>
<div id="o-que-muda-nas-funções-t.test-e-wilcox.test" class="section level3 hasAnchor" number="20.5.4">
<h3><span class="header-section-number">20.5.4</span> O que muda nas funções <code>t.test()</code> e <code>wilcox.test()</code><a href="comparação-entre-dois-grupos.html#o-que-muda-nas-funções-t.test-e-wilcox.test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Nas duas funções, você controla o tipo de teste pelo argumento <code>alternative</code>:</p>
<ul>
<li><strong>Teste bilateral (padrão):</strong>
<ul>
<li><code>alternative = "two.sided"</code></li>
</ul></li>
<li><strong>Teste unilateral (maior):</strong>
<ul>
<li><code>alternative = "greater"</code></li>
</ul></li>
<li><strong>Teste unilateral (menor):</strong>
<ul>
<li><code>alternative = "less"</code></li>
</ul></li>
</ul>
<p><strong>Exemplo:</strong></p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="comparação-entre-dois-grupos.html#cb101-1" tabindex="-1"></a><span class="co"># Teste t bilateral (padrão)</span></span>
<span id="cb101-2"><a href="comparação-entre-dois-grupos.html#cb101-2" tabindex="-1"></a><span class="fu">t.test</span>(x, y, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span>
<span id="cb101-3"><a href="comparação-entre-dois-grupos.html#cb101-3" tabindex="-1"></a></span>
<span id="cb101-4"><a href="comparação-entre-dois-grupos.html#cb101-4" tabindex="-1"></a><span class="co"># Teste t unilateral (x maior que y)</span></span>
<span id="cb101-5"><a href="comparação-entre-dois-grupos.html#cb101-5" tabindex="-1"></a><span class="fu">t.test</span>(x, y, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span>
<span id="cb101-6"><a href="comparação-entre-dois-grupos.html#cb101-6" tabindex="-1"></a></span>
<span id="cb101-7"><a href="comparação-entre-dois-grupos.html#cb101-7" tabindex="-1"></a><span class="co"># Teste de Wilcoxon unilateral (x menor que y)</span></span>
<span id="cb101-8"><a href="comparação-entre-dois-grupos.html#cb101-8" tabindex="-1"></a><span class="fu">wilcox.test</span>(x, y, <span class="at">alternative =</span> <span class="st">&quot;less&quot;</span>)</span></code></pre></div>
<p>Ou seja:
- <strong>O argumento <code>alternative</code> define se o teste é bilateral ou unilateral.</strong>
- Isso altera a formulação das hipóteses, o cálculo do p-valor e a interpretação do resultado.</p>
</div>
</div>
<div id="exercício-1" class="section level2 hasAnchor" number="20.6">
<h2><span class="header-section-number">20.6</span> Exercício 1<a href="comparação-entre-dois-grupos.html#exercício-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Comparação da velocidade dos Pokémons verdes e amarelos</strong></p>
<ol style="list-style-type: decimal">
<li><p><strong>Baixe o banco de dados</strong><br />
Use o banco de dados: <a href="https://drive.google.com/drive/folders/1gyORbBEuKBstfSKULA58TLhawOXaY-st">Pokemon.csv</a><br />
Importe o arquivo <strong>Pokemon.csv</strong> para o RStudio.</p></li>
<li><p><strong>Pergunta do exercício</strong><br />
Teste se existe diferença significativa entre a velocidade (<strong>speed</strong>) dos Pokémons verdes (<strong>green</strong>) e amarelos (<strong>yellow</strong>).</p></li>
<li><p><strong>Formulação das hipóteses de acordo com os testes</strong></p>
<blockquote>
<p>Hipótese nula (<span class="math inline">\(H_0\)</span>):</p>
</blockquote>
<blockquote>
<p>Hipótese alternativa (<span class="math inline">\(H_1\)</span>):</p>
</blockquote></li>
<li><p><strong>Nível de significância</strong><br />
Considere <span class="math inline">\(\alpha = 0,05\)</span>.</p></li>
<li><p><strong>Passos para executar o teste adequado</strong></p>
<ol style="list-style-type: lower-alpha">
<li>Separe os dados dos Pokémons de cor verde e de cor amarela.<br />
</li>
<li>Verifique a normalidade dos dados de velocidade de cada grupo (gráfico QQ).<br />
</li>
<li>Escolha o teste mais apropriado:
<ul>
<li>Se as duas amostras seguirem distibuição Normal → teste de variância → teste t</li>
<li>Se uma das amostras não seguir distibuição Normal → teste de Wilcoxon</li>
</ul></li>
<li>Execute o teste, compare o p-valor com <span class="math inline">\(\alpha\)</span> e conclua</li>
</ol></li>
<li><p><strong>Conclusão</strong></p>
<ul>
<li>Se <span class="math inline">\(p\)</span>-valor &lt; 0,05: rejeite a hipótese nula e conclua que há diferença significativa nas velocidades.</li>
<li>Se <span class="math inline">\(p\)</span>-valor ≥ 0,05: não rejeite a hipótese nula e conclua que não há diferença significativa nas velocidades.</li>
</ul></li>
</ol>
<p><strong>Resposta</strong> <a href="https://posit.cloud/content/10470490">Posit.cloud</a></p>
</div>
<div id="exercício-2" class="section level2 hasAnchor" number="20.7">
<h2><span class="header-section-number">20.7</span> Exercício 2<a href="comparação-entre-dois-grupos.html#exercício-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Considere a tabela de resultados publicados no artigo <a href="https://www.google.com/search?q=teste+t+medicina+artigo+&amp;sca_esv=e5b91424496cf486&amp;ei=2bREaLDDNsnX5OUPnpW78Ac&amp;ved=0ahUKEwjwk8eEpuCNAxXJK7kGHZ7KDn4Q4dUDCBA&amp;uact=5&amp;oq=teste+t+medicina+artigo+&amp;gs_lp=Egxnd3Mtd2l6LXNlcnAiGHRlc3RlIHQgbWVkaWNpbmEgYXJ0aWdvIDIHECEYoAEYCjIHECEYoAEYCjIFECEYnwVIlhdQrQlY4BVwAngBkAEAmAG6AaABrwmqAQMwLji4AQPIAQD4AQGYAgqgAt8JwgIKEAAYsAMY1gQYR8ICBRAhGKABwgIIEAAYCBgNGB7CAgUQABjvBcICCBAAGIAEGKIEmAMAiAYBkAYIkgcDMi44oAflIrIHAzAuOLgH1gnCBwUwLjcuM8gHHA&amp;sclient=gws-wiz-serp#:~:text=Resposta%20da%20Press%C3%A3o,br%20%E2%80%BA%20abc">Resposta da Pressão Arterial ao Esforço em Adolescentes: Influência do Sobrepeso e Obesidade</a>:</p>
<table>
<colgroup>
<col width="31%" />
<col width="28%" />
<col width="27%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th>Grupo</th>
<th align="center">GSO Meninas (n = 24)</th>
<th align="center">GE Meninas (n = 24)</th>
<th align="center">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Idade</strong> (anos)</td>
<td align="center">12,1 ± 1,3</td>
<td align="center">12,0 ± 1,5</td>
<td align="center">0,86</td>
</tr>
<tr class="even">
<td><strong>Peso</strong> (kg)</td>
<td align="center">59,3 ± 12,9</td>
<td align="center">38,8 ± 9,3**</td>
<td align="center">&lt;0,0001</td>
</tr>
<tr class="odd">
<td><strong>Estatura</strong> (m)</td>
<td align="center">1,53 ± 0,09</td>
<td align="center">1,46 ± 0,10*</td>
<td align="center">0,02</td>
</tr>
<tr class="even">
<td><strong>IMC</strong> (kg/m²)</td>
<td align="center">25,2 ± 3,8</td>
<td align="center">17,9 ± 2,3**</td>
<td align="center">&lt;0,0001</td>
</tr>
<tr class="odd">
<td><strong>RT/S</strong> (mm)</td>
<td align="center">0,85 ± 0,19</td>
<td align="center">1,43 ± 0,40**</td>
<td align="center">&lt;0,0001</td>
</tr>
<tr class="even">
<td><strong>PAS repouso</strong> (mmHg)</td>
<td align="center">114 ± 12</td>
<td align="center">108 ± 10</td>
<td align="center">0,07</td>
</tr>
<tr class="odd">
<td><strong>PAD repouso</strong> (mmHg)</td>
<td align="center">66 ± 6</td>
<td align="center">67 ± 8</td>
<td align="center">0,51</td>
</tr>
<tr class="even">
<td><strong>PAM repouso</strong> (mmHg)</td>
<td align="center">82 ± 7</td>
<td align="center">81 ± 8</td>
<td align="center">0,67</td>
</tr>
<tr class="odd">
<td><strong>FC</strong> (bpm)</td>
<td align="center">84 ± 10</td>
<td align="center">87 ± 9</td>
<td align="center">0,34</td>
</tr>
</tbody>
</table>
<p><em>Teste t-Student para amostras independentes; </em>p ≤ 0,05; **p ≤ 0,01.<br />
Diferenças entre médias do grupo de sobrepeso e obesos vs eutróficos.</p>
<p>IMC - índice de massa corporal (peso/estatura²);</p>
<p>RT/S - relação tríceps/subescapular;</p>
<p>PAS - pressão arterial sistólica;</p>
<p>PAD - pressão arterial diastólica;</p>
<p>PAM - pressão arterial média;</p>
<p>FC - frequência cardíaca média.*</p>
<p><strong>Contexto:</strong><br />
A tabela acima apresenta características antropométricas e hemodinâmicas de meninas do grupo de sobrepeso/obesidade (GSO) e do grupo eutrófico (GE). Os autores utilizaram o teste t de Student para amostras independentes.</p>
<p><strong>Pergunta:</strong><br />
Escolha uma variável da tabela e formule as hipóteses nula e alternativa para a comparação entre os grupos GSO e GE. Depois, descreva a conclusão dos autores com base no valor de p apresentado na tabela.</p>
<hr />
<p><strong>Exemplo de resposta:</strong></p>
<p><strong>Variável escolhida:</strong> Peso (kg)</p>
<p><strong>Hipóteses:</strong></p>
<ul>
<li><p>Hipótese nula (H₀):<br />
As médias de peso (kg) dos grupos GSO e GE são iguais.</p></li>
<li><p>Hipótese alternativa (H₁):<br />
As médias de peso (kg) dos grupos GSO e GE são diferentes.</p></li>
</ul>
<p><strong>Nível de significância:</strong> α = 0,05</p>
<p><strong>Valor de p na tabela:</strong> p &lt; 0,0001</p>
<p><strong>Conclusão:</strong><br />
Como o valor de p é menor que 0,05, rejeita-se a hipótese nula. Portanto, os autores concluem que existe diferença estatisticamente significativa entre as médias de peso dos grupos GSO e GE, sendo o peso significativamente maior no grupo GSO.</p>
<p><strong>Você pensou nisso?</strong>
O peso é a variável intrínseca à comparação, pois define os grupos.</p>
<hr />
</div>
<div id="exercício-3" class="section level2 hasAnchor" number="20.8">
<h2><span class="header-section-number">20.8</span> Exercício 3<a href="comparação-entre-dois-grupos.html#exercício-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O artigo <a href="https://www.scielo.br/j/rbce/a/WkdgtTdkykSVHJ9rGYGh7Lx/?format=pdf&amp;lang=pt">Sintomas de estresse pré-competitivo em atletas adolescentes de handebol</a> utilizou como instrumento a Lista de Sintomas de Estresse Pré-competitivo Infanto-juvenil (LSSPCI), uma escala do tipo Likert (De Rose Jr., 1998). A LSSPCI contém 31 sintomas, para os quais cada atleta responde em uma escala de 1 (nunca) a 5 (sempre) sobre a frequência com que cada situação ocorreu nas 24 horas anteriores à competição. Os escores dos sintomas são somados para cada atleta, resultando em um escore total de estresse. Analise os resultados da Tabela 1 do artigo:</p>
<p><strong>Tabela 1. Médias, desvios-padrão, valores p da diferença de médias e mediana dos sintomas de estresse medidos pela LSSPCI em atletas adolescentes de handebol, segundo o sexo (n = 97)</strong></p>
<table>
<colgroup>
<col width="43%" />
<col width="24%" />
<col width="24%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th>Sintomas de estresse – LSSPCI</th>
<th align="center">Meninos</th>
<th align="center">Meninas</th>
<th align="center">Valor pᵃ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Meu coração bate mais rápido que o normal</td>
<td align="center">2,2 ± 1,0 (2,0)</td>
<td align="center">2,5 ± 0,9 (2,5)</td>
<td align="center">0,1</td>
</tr>
<tr class="even">
<td>Suo bastante</td>
<td align="center">2,5 ± 1,2 (2,0)</td>
<td align="center">2,4 ± 1,3 (2,0)</td>
<td align="center">0,4</td>
</tr>
<tr class="odd">
<td>Fico agitado (a)</td>
<td align="center">3,0 ± 0,9 (3,0)</td>
<td align="center">3,2 ± 1,3 (3,0)</td>
<td align="center">0,5</td>
</tr>
<tr class="even">
<td>Fico preocupado (a) com críticas das pessoas</td>
<td align="center">2,9 ± 1,5 (3,0)</td>
<td align="center">2,6 ± 1,4 (2,0)</td>
<td align="center">0,2</td>
</tr>
<tr class="odd">
<td>Sinto muita vontade de fazer xixi</td>
<td align="center">2,0 ± 1,3 (1,0)</td>
<td align="center">2,0 ± 1,2 (2,0)</td>
<td align="center">0,7</td>
</tr>
<tr class="even">
<td>Fico preocupado (a) com meus adversários</td>
<td align="center">2,7 ± 1,2 (3,0)</td>
<td align="center">2,9 ± 1,4 (3,0)</td>
<td align="center">0,5</td>
</tr>
<tr class="odd">
<td>Bebo muita água</td>
<td align="center">2,5 ± 1,2 (3,0)</td>
<td align="center">2,9 ± 1,5 (3,0)</td>
<td align="center">0,3</td>
</tr>
<tr class="even">
<td>Roo (como) as unhas</td>
<td align="center">2,5 ± 1,9 (2,0)</td>
<td align="center">2,1 ± 1,5 (1,0)</td>
<td align="center">0,2</td>
</tr>
<tr class="odd">
<td>Fico empolgado (a)</td>
<td align="center">3,5 ± 1,3 (4,0)</td>
<td align="center">3,6 ± 1,5 (4,0)</td>
<td align="center">0,6</td>
</tr>
<tr class="even">
<td>Fico aflito (a)</td>
<td align="center">2,3 ± 1,7 (2,0)</td>
<td align="center">2,8 ± 1,3 (3,0)</td>
<td align="center">0,1</td>
</tr>
<tr class="odd">
<td>Tenho medo de competir mal</td>
<td align="center">2,6 ± 1,4 (3,0)</td>
<td align="center">2,9 ± 1,4 (3,0)</td>
<td align="center">0,4</td>
</tr>
<tr class="even">
<td>Demoro muito para dormir</td>
<td align="center">2,8 ± 2,4 (3,0)</td>
<td align="center">2,3 ± 2,0 (2,0)</td>
<td align="center">0,05</td>
</tr>
<tr class="odd">
<td>Tenho dúvidas sobre minha capacidade de competir</td>
<td align="center">2,4 ± 1,8 (2,0)</td>
<td align="center">2,4 ± 1,2 (2,0)</td>
<td align="center">0,7</td>
</tr>
<tr class="even">
<td>Sonho com a competição</td>
<td align="center">2,4 ± 1,2 (2,0)</td>
<td align="center">1,9 ± 1,3 (1,0)</td>
<td align="center">0,04</td>
</tr>
<tr class="odd">
<td>Fico nervoso (a)</td>
<td align="center">3,1 ± 1,6 (3,0)</td>
<td align="center">3,3 ± 1,2 (3,0)</td>
<td align="center">0,6</td>
</tr>
<tr class="even">
<td>Fico preocupado (a) com o resultado da competição</td>
<td align="center">3,1 ± 1,4 (3,0)</td>
<td align="center">3,7 ± 1,4 (4,0)</td>
<td align="center">0,1</td>
</tr>
<tr class="odd">
<td>Minha boca fica seca</td>
<td align="center">2,4 ± 1,3 (2,0)</td>
<td align="center">2,3 ± 1,4 (2,0)</td>
<td align="center">0,6</td>
</tr>
<tr class="even">
<td>Sinto muito cansaço no fim do treino</td>
<td align="center">2,6 ± 1,3 (2,0)</td>
<td align="center">2,7 ± 1,3 (2,0)</td>
<td align="center">0,9</td>
</tr>
<tr class="odd">
<td>A presença de meus pais na competição me preocupa</td>
<td align="center">3,1 ± 1,7 (2,0)</td>
<td align="center">2,6 ± 1,6 (2,0)</td>
<td align="center">0,1</td>
</tr>
<tr class="even">
<td>Falo muito sobre a competição</td>
<td align="center">3,0 ± 1,5 (3,0)</td>
<td align="center">3,2 ± 1,3 (3,0)</td>
<td align="center">0,6</td>
</tr>
<tr class="odd">
<td>Tenho medo de perder</td>
<td align="center">2,9 ± 1,4 (3,0)</td>
<td align="center">3,1 ± 1,4 (3,0)</td>
<td align="center">0,4</td>
</tr>
<tr class="even">
<td>Fico impaciente</td>
<td align="center">2,4 ± 1,1 (2,0)</td>
<td align="center">2,6 ± 1,3 (2,5)</td>
<td align="center">0,5</td>
</tr>
<tr class="odd">
<td>Não penso em outra coisa a não ser na competição</td>
<td align="center">2,2 ± 1,2 (2,0)</td>
<td align="center">2,7 ± 1,4 (2,0)</td>
<td align="center">0,2</td>
</tr>
<tr class="even">
<td>Não vejo a hora de competir</td>
<td align="center">3,2 ± 1,4 (3,0)</td>
<td align="center">3,3 ± 1,4 (3,0)</td>
<td align="center">0,7</td>
</tr>
<tr class="odd">
<td>Fico emocionado (a)</td>
<td align="center">1,8 ± 1,3 (1,0)</td>
<td align="center">2,3 ± 1,3 (2,0)</td>
<td align="center">0,1</td>
</tr>
<tr class="even">
<td>Fico ansioso (a)</td>
<td align="center">3,6 ± 1,2 (3,0)</td>
<td align="center">3,4 ± 1,5 (4,0)</td>
<td align="center">0,7</td>
</tr>
<tr class="odd">
<td>No dia da competição acordo mais cedo do que o normal</td>
<td align="center">3,1 ± 1,7 (3,0)</td>
<td align="center">3,0 ± 1,6 (3,0)</td>
<td align="center">0,8</td>
</tr>
<tr class="even">
<td>Tenho medo de decepcionar as pessoas</td>
<td align="center">2,7 ± 1,4 (3,0)</td>
<td align="center">3,0 ± 1,5 (3,0)</td>
<td align="center">0,3</td>
</tr>
<tr class="odd">
<td>Sinto-me mais responsável</td>
<td align="center">3,1 ± 1,3 (3,0)</td>
<td align="center">2,7 ± 1,3 (3,0)</td>
<td align="center">0,2</td>
</tr>
<tr class="even">
<td>Sinto que as pessoas exigem muito de mim</td>
<td align="center">2,5 ± 1,4 (2,0)</td>
<td align="center">2,4 ± 1,4 (2,0)</td>
<td align="center">0,8</td>
</tr>
<tr class="odd">
<td>Tenho medo de cometer erros na competição</td>
<td align="center">3,4 ± 1,4 (3,0)</td>
<td align="center">3,6 ± 1,3 (4,0)</td>
<td align="center">0,4</td>
</tr>
</tbody>
</table>
<p>Média ± DP (mediana); ᵃ Teste de Wilcoxon não pareado; p &lt; 0,05.</p>
<p><strong>Com base na Tabela 1, qual sintoma de estresse apresentou diferença estatisticamente significativa entre meninos e meninas segundo o teste de Wilcoxon? Explique como interpretar esse resultado considerando o contexto da escala LSSPCI.</strong></p>
</div>
<div id="exercício-4" class="section level2 hasAnchor" number="20.9">
<h2><span class="header-section-number">20.9</span> Exercício 4<a href="comparação-entre-dois-grupos.html#exercício-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O artigo <a href="https://pepsic.bvsalud.org/pdf/psicoinfo/v16n16/v16n16a07.pdf">Qualidade de vida de estudantes de Psicologia</a> avaliou a qualidade de vida de acadêmicos de psicologia e correlacionou-a com fatores sociodemográficos. Participaram 310 alunos de psicologia que responderam a um questionário sociodemográfico e ao The Medical Outcomes Study 36-item Short-Form Health Survey (SF-36) para avaliar a qualidade de vida. Veja os resultados do teste t na Tabela 2:</p>
<p><strong>Tabela 2: Comparação entre gêneros nas dimensões de qualidade de vida</strong></p>
<table>
<colgroup>
<col width="29%" />
<col width="17%" />
<col width="14%" />
<col width="14%" />
<col width="10%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th>Dimensões</th>
<th align="center">Variável</th>
<th align="center">Média</th>
<th align="center">DP</th>
<th align="center">t</th>
<th align="center">p-valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Capacidade funcional</td>
<td align="center">Masculino</td>
<td align="center">89,74</td>
<td align="center">14,49</td>
<td align="center">2,44</td>
<td align="center">0,119</td>
</tr>
<tr class="even">
<td></td>
<td align="center">Feminino</td>
<td align="center">86,95</td>
<td align="center">11,6</td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td>Aspectos físicos</td>
<td align="center">Masculino</td>
<td align="center">79,74</td>
<td align="center">25,84</td>
<td align="center">0,76</td>
<td align="center">0,383</td>
</tr>
<tr class="even">
<td></td>
<td align="center">Feminino</td>
<td align="center">75,82</td>
<td align="center">31,84</td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td>Dor</td>
<td align="center">Masculino</td>
<td align="center">74,93</td>
<td align="center">22,05</td>
<td align="center">4,33</td>
<td align="center">0,038</td>
</tr>
<tr class="even">
<td></td>
<td align="center">Feminino</td>
<td align="center">68,26</td>
<td align="center">22,00</td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td>Estado geral de saúde</td>
<td align="center">Masculino</td>
<td align="center">75,21</td>
<td align="center">20,36</td>
<td align="center">1,15</td>
<td align="center">0,284</td>
</tr>
<tr class="even">
<td></td>
<td align="center">Feminino</td>
<td align="center">72,32</td>
<td align="center">17,67</td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td>Vitalidade</td>
<td align="center">Masculino</td>
<td align="center">61,38</td>
<td align="center">22,47</td>
<td align="center">1,50</td>
<td align="center">0,222</td>
</tr>
<tr class="even">
<td></td>
<td align="center">Feminino</td>
<td align="center">57,92</td>
<td align="center">18,57</td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td>Aspectos sociais</td>
<td align="center">Masculino</td>
<td align="center">71,34</td>
<td align="center">27,61</td>
<td align="center">0,06</td>
<td align="center">0,804</td>
</tr>
<tr class="even">
<td></td>
<td align="center">Feminino</td>
<td align="center">70,43</td>
<td align="center">24,31</td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td>Aspecto emocional</td>
<td align="center">Masculino</td>
<td align="center">63,16</td>
<td align="center">40,67</td>
<td align="center">0,38</td>
<td align="center">0,536</td>
</tr>
<tr class="even">
<td></td>
<td align="center">Feminino</td>
<td align="center">59,51</td>
<td align="center">39,85</td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td>Saúde mental</td>
<td align="center">Masculino</td>
<td align="center">70,55</td>
<td align="center">19,97</td>
<td align="center">3,05</td>
<td align="center">0,082</td>
</tr>
<tr class="even">
<td></td>
<td align="center">Feminino</td>
<td align="center">65,7</td>
<td align="center">18,80</td>
<td align="center"></td>
<td align="center"></td>
</tr>
</tbody>
</table>
<p><strong>Com base na Tabela 2, em qual dimensão da qualidade de vida foi observada diferença estatisticamente significativa entre estudantes do sexo masculino e feminino? O que esse resultado sugere sobre a experiência dos alunos nesses grupos?</strong></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="testes-de-comparação-entre-grupos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="cálculo-amostral-no-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": false,
    "linkedin": true,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": true,
    "all": ["twitter", "linkedin", "whatsapp", "github", "facebook"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["LivroEstatisticaR.pdf", "LivroEstatisticaR.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "language": "pt-BR",
  "info": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
